/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package organizadorBoda.formularios;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Nico
 */
public class FormularioClientes extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioClientes.class.getName());

    /**
     * Creates new form FormularioClientes
     */
    public FormularioClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosPersonalesPnl = new javax.swing.JPanel();
        NombreLbl = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        telefonoLbl = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        detallesBodaPnl = new javax.swing.JPanel();
        fechaLbl = new javax.swing.JLabel();
        fechaSpn = new javax.swing.JSpinner();
        presupuestoLbl = new javax.swing.JLabel();
        presupuestoCmb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        invitadosSpn = new javax.swing.JSpinner();
        cateringLbl = new javax.swing.JLabel();
        cateringComb = new javax.swing.JComboBox<>();
        habitacionesChb = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        decoracionLbl = new javax.swing.JLabel();
        musicaCmb = new javax.swing.JComboBox<>();
        decoracionCmb = new javax.swing.JComboBox<>();
        accionesPnl = new javax.swing.JPanel();
        guardarDatosBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        datosPersonalesPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));
        datosPersonalesPnl.setName("datosPersonalesPnl"); // NOI18N
        datosPersonalesPnl.setLayout(null);

        NombreLbl.setText("Nombre Completo: ");
        NombreLbl.setToolTipText("");
        datosPersonalesPnl.add(NombreLbl);
        NombreLbl.setBounds(20, 60, 130, 16);

        nombreTxt.setToolTipText("Introduce tu nombre y apellidos");
        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });
        datosPersonalesPnl.add(nombreTxt);
        nombreTxt.setBounds(180, 60, 170, 22);

        telefonoLbl.setText("Telefono: ");
        telefonoLbl.setToolTipText("Introduce tu numero de telefono");
        datosPersonalesPnl.add(telefonoLbl);
        telefonoLbl.setBounds(20, 110, 90, 16);
        datosPersonalesPnl.add(telefonoTxt);
        telefonoTxt.setBounds(180, 110, 170, 22);

        detallesBodaPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles de la boda"));

        fechaLbl.setText("Fecha: ");

        fechaSpn.setModel(new javax.swing.SpinnerDateModel());

        presupuestoLbl.setText("Presupuesto: ");

        presupuestoCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menos de 5.000 $", "5.000 $ - 10.000 $", "10.000 $ - 20.000 $", "Mas de 20.000$" }));

        jLabel1.setText("Numero de invitados: ");

        invitadosSpn.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        cateringLbl.setText("Catering: ");

        cateringComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu establecido", "Negociacion con el chef", "Buffet" }));

        habitacionesChb.setText("Habitaciones");

        jLabel2.setText("Musica: ");

        decoracionLbl.setText("Decoracion: ");

        musicaCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dj", "Banda en vivo", "Ninguno" }));

        decoracionCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clasica", "Moderna", "Tematica" }));

        javax.swing.GroupLayout detallesBodaPnlLayout = new javax.swing.GroupLayout(detallesBodaPnl);
        detallesBodaPnl.setLayout(detallesBodaPnlLayout);
        detallesBodaPnlLayout.setHorizontalGroup(
            detallesBodaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detallesBodaPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detallesBodaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detallesBodaPnlLayout.createSequentialGroup()
                        .addGroup(detallesBodaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(presupuestoLbl)
                            .addComponent(jLabel1)
                            .addComponent(cateringLbl)
                            .addComponent(jLabel2)
                            .addComponent(decoracionLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(detallesBodaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaSpn)
                            .addComponent(invitadosSpn)
                            .addComponent(presupuestoCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cateringComb, 0, 1, Short.MAX_VALUE)
                            .addComponent(musicaCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(decoracionCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(117, 117, 117))
                    .addGroup(detallesBodaPnlLayout.createSequentialGroup()
                        .addComponent(habitacionesChb)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        detallesBodaPnlLayout.setVerticalGroup(
            detallesBodaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detallesBodaPnlLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(detallesBodaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLbl)
                    .addComponent(fechaSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detallesBodaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presupuestoLbl)
                    .addComponent(presupuestoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detallesBodaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(invitadosSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detallesBodaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cateringLbl)
                    .addComponent(cateringComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detallesBodaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(musicaCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detallesBodaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decoracionLbl)
                    .addComponent(decoracionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(habitacionesChb)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        accionesPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        guardarDatosBtn.setText("Guardar Datos");
        guardarDatosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDatosBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accionesPnlLayout = new javax.swing.GroupLayout(accionesPnl);
        accionesPnl.setLayout(accionesPnlLayout);
        accionesPnlLayout.setHorizontalGroup(
            accionesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionesPnlLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(accionesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardarDatosBtn)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accionesPnlLayout.createSequentialGroup()
                        .addComponent(cancelarBtn)
                        .addGap(14, 14, 14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accionesPnlLayout.setVerticalGroup(
            accionesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionesPnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(guardarDatosBtn)
                .addGap(18, 18, 18)
                .addComponent(cancelarBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datosPersonalesPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detallesBodaPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(accionesPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(datosPersonalesPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detallesBodaPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accionesPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void guardarDatosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDatosBtnActionPerformed
        String nombre = nombreTxt.getText();
        String telefono = telefonoTxt.getText();
        Date fecha = (Date) fechaSpn.getValue();
        String presupuesto = (String) presupuestoCmb.getSelectedItem();
        int invitados = (Integer) invitadosSpn.getValue();
        String catering = (String) cateringComb.getSelectedItem();
        boolean habitaciones = habitacionesChb.isSelected();
        String musica = (String) musicaCmb.getSelectedItem();
        String decoracion = (String) decoracionCmb.getSelectedItem();

        JOptionPane.showMessageDialog(this,
            "Datos del cliente:\n" +
            "Nombre: " + nombre + "\n" +
            "Teléfono: " + telefono + "\n" +
            "Fecha: " + fecha + "\n" +
            "Presupuesto: " + presupuesto + "\n" +
            "Invitados: " + invitados + "\n" +
            "Catering: " + catering + "\n" +
            "Habitaciones: " + (habitaciones ? "Sí" : "No") + "\n" +
            "Música: " + musica + "\n" +
            "Decoración: " + decoracion
        );
    }//GEN-LAST:event_guardarDatosBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioClientes dialog = new FormularioClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NombreLbl;
    private javax.swing.JPanel accionesPnl;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JComboBox<String> cateringComb;
    private javax.swing.JLabel cateringLbl;
    private javax.swing.JPanel datosPersonalesPnl;
    private javax.swing.JComboBox<String> decoracionCmb;
    private javax.swing.JLabel decoracionLbl;
    private javax.swing.JPanel detallesBodaPnl;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JSpinner fechaSpn;
    private javax.swing.JButton guardarDatosBtn;
    private javax.swing.JCheckBox habitacionesChb;
    private javax.swing.JSpinner invitadosSpn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> musicaCmb;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JComboBox<String> presupuestoCmb;
    private javax.swing.JLabel presupuestoLbl;
    private javax.swing.JLabel telefonoLbl;
    private javax.swing.JTextField telefonoTxt;
    // End of variables declaration//GEN-END:variables
}
