/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio2;

/**
 *
 * @author Nico
 */
public class Ejercicio2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ejercicio2.class.getName());

    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        seriesBtn = new javax.swing.JCheckBox();
        peliculasBtn = new javax.swing.JCheckBox();
        noticiasBtn = new javax.swing.JCheckBox();
        novelasBtn = new javax.swing.JCheckBox();
        confirmarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        seriesBtn.setText("Series");
        jPanel1.add(seriesBtn);

        peliculasBtn.setText("Peliculas");
        jPanel1.add(peliculasBtn);

        noticiasBtn.setText("Noticias");
        jPanel1.add(noticiasBtn);

        novelasBtn.setText("Novelas");
        jPanel1.add(novelasBtn);

        confirmarBtn.setText("Confirmar");
        confirmarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(confirmarBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBtnActionPerformed
        StringBuilder lista = new StringBuilder ("Lo seleccionado:\n ");
        if(seriesBtn.isSelected()){
            lista.append("-series\n");
        }
        if(peliculasBtn.isSelected()) {
            lista.append("- peliculas\n");
        }
        if(noticiasBtn.isSelected()){
            lista.append("- noticias\n");
        }
        if(novelasBtn.isSelected()) {
            lista.append("- novela\n");
        }
        
        
        javax.swing.JOptionPane.showMessageDialog(this, lista.toString(), "preferencias" , javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_confirmarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ejercicio2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmarBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox noticiasBtn;
    private javax.swing.JCheckBox novelasBtn;
    private javax.swing.JCheckBox peliculasBtn;
    private javax.swing.JCheckBox seriesBtn;
    // End of variables declaration//GEN-END:variables
}
